### ISSUE TITLE
Add a GSOD-19 page

### ISSUE THREAD

**Issue by Mec-iS** [http-apis-docs/gsod#2]
Write a GSOD-19 page for the website to present the Project Ideas

**Comment by de-sh** [comment]
What are your thoughts on making use of Read the Docs. Or should we instead use our own choice of Jekyll theme(The one used by @xadahiya on hydraecosystem.org) for this?

**Comment by Mec-iS** [comment]
Done in https://github.com/HTTP-APIs/http-apis.github.io/pull/29
